vich_uploader:
    db_driver: orm
    mappings:
        images:
            # uri_prefix: '%app.path.images%'
            uri_prefix: 'http://localhost:8000/uploads'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
            namer:
                service: vich_uploader.namer_origname
                options: { algorithm: 'sha256', length: 50 }